name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 3 1 * *'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  |
          docker login --username FlemmingKrarup --password ${{ secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/flemmingkrarup/cups:latest
          docker push ghcr.io/flemmingkrarup/cups:latest

      
    #docker build . --file Dockerfile --tag my-image-name:$(date +%s)
